# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
